language: python
python:
  - 2.4
  - 2.6
  - 2.7
  - pypy
  - 3.1
  - 3.2
  - 3.3
  - 3.4
# command to run tests
script:
 # update egg_info based on setup.py in checkout
 - python bootstrap.py

 - python setup.py test --addopts='-rs'
 - python ez_setup.py --version 12.2
